service: auction-service
frameworkVersion: '3'

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs20.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION, 'us-east-2'}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:PutItem
    Resource:
      - arn:aws:dynamodb:${aws:accountId}:${aws:region}:table/AuctionsTable      

functions:
  hello:
    handler: src/handlers/handler.hello
    architecture: arm64
    events:
      - httpApi:
          path: /
          method: get
  createAuction:
    handler: src/handlers/handler.createAuction
    architecture: arm64
    events:
      - httpApi:
          path: /auction
          method: post

resources:
  Resources:
    AuctionsTable: #logical name
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-plugin-typescript
  - serverless-offline
