service: auction-service
frameworkVersion: '3'

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs20.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  #profile: yuriy-admin
  region: ${env:AWS_REGION, 'us-east-2'}
  

functions:
  hello:
    handler: src/handlers/handler.hello
    architecture: arm64
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
